name: "Terraform CI"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  terraform-checks:
    name: "Terraform Format, Validate & Autocommit"
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./terraform

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      # Step 3: Check Terraform code formatting
      - name: Terraform Auto Format
        run: terraform fmt -recursive

      # Step 4: Initialize Terraform (without connecting to real cloud backend)
      - name: Commit Formatted Code
        uses: stefanzweifel/git-autocommit-action@v5
        with:
          commit_message: "Style: auto-format Terraform files [skip ci]"
          file_pattern: "*.tf *tfvars"
      # Step 5: Run Tfsec (Security Scan for misconfig like public S3 or SG rules)
      - name: Run Tfsec Security Scan
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: ./terraform
          soft_fail: true

      # Step 5: Initialize Terraform (without connecting to real cloud backend)
      - name: Terraform Init
        run: terraform init -backend=false

      # Step 6: Validate syntax and structure
      - name: Terraform Validate
        run: terraform validate
